// Thin re-export so the rest of the app imports from a stable path.
// The actual client is generated by Lovable Cloud at src/integrations/supabase/client.
import { supabase } from "@/integrations/supabase/client";

export { supabase };

export const isSupabaseConfigured = (): boolean => {
  return Boolean(
    import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  );
};
