/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MapRouteImport } from './routes/map'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as EarthquakesRouteImport } from './routes/earthquakes'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGnewsProxyRouteImport } from './routes/api/public/gnews-proxy'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthquakesRoute = EarthquakesRouteImport.update({
  id: '/earthquakes',
  path: '/earthquakes',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGnewsProxyRoute = ApiPublicGnewsProxyRouteImport.update({
  id: '/api/public/gnews-proxy',
  path: '/api/public/gnews-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/earthquakes': typeof EarthquakesRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/weather': typeof WeatherRoute
  '/api/public/gnews-proxy': typeof ApiPublicGnewsProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/earthquakes': typeof EarthquakesRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/weather': typeof WeatherRoute
  '/api/public/gnews-proxy': typeof ApiPublicGnewsProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/earthquakes': typeof EarthquakesRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/saved': typeof SavedRoute
  '/weather': typeof WeatherRoute
  '/api/public/gnews-proxy': typeof ApiPublicGnewsProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/compare'
    | '/countries'
    | '/earthquakes'
    | '/intelligence'
    | '/map'
    | '/saved'
    | '/weather'
    | '/api/public/gnews-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/compare'
    | '/countries'
    | '/earthquakes'
    | '/intelligence'
    | '/map'
    | '/saved'
    | '/weather'
    | '/api/public/gnews-proxy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/compare'
    | '/countries'
    | '/earthquakes'
    | '/intelligence'
    | '/map'
    | '/saved'
    | '/weather'
    | '/api/public/gnews-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  CompareRoute: typeof CompareRoute
  CountriesRoute: typeof CountriesRoute
  EarthquakesRoute: typeof EarthquakesRoute
  IntelligenceRoute: typeof IntelligenceRoute
  MapRoute: typeof MapRoute
  SavedRoute: typeof SavedRoute
  WeatherRoute: typeof WeatherRoute
  ApiPublicGnewsProxyRoute: typeof ApiPublicGnewsProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earthquakes': {
      id: '/earthquakes'
      path: '/earthquakes'
      fullPath: '/earthquakes'
      preLoaderRoute: typeof EarthquakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gnews-proxy': {
      id: '/api/public/gnews-proxy'
      path: '/api/public/gnews-proxy'
      fullPath: '/api/public/gnews-proxy'
      preLoaderRoute: typeof ApiPublicGnewsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  CompareRoute: CompareRoute,
  CountriesRoute: CountriesRoute,
  EarthquakesRoute: EarthquakesRoute,
  IntelligenceRoute: IntelligenceRoute,
  MapRoute: MapRoute,
  SavedRoute: SavedRoute,
  WeatherRoute: WeatherRoute,
  ApiPublicGnewsProxyRoute: ApiPublicGnewsProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
